#define blud main
#define skibidi {
#define gucci }
#define rn ;
#define cap 0
#define no !
#define bouta &
#define bussin !=
#define be ==
#define sus <
#define uwu <=
#define slaps --
#define ong ++
#define finna =
#define yeet +
#define slay *
#define yap %
#define rizz printf
#define fam int
#define lit char
#define bet if
#define fanum while
#define ngl for
#define frfr long
#define flat return
#define cook continue
#define bigyikes break
#define nah void
#define oop sizeof
#define sigma scanf
#define stan getchar
#define pookie malloc